#ifdef __INTELLISENSE__
#include <Windows.h>
#include "GL/glcorearb.h"
#define X(type, name) type name;
#endif

X(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays)
X(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray)
X(PFNGLGENBUFFERSPROC, glGenBuffers)
X(PFNGLBINDBUFFERPROC, glBindBuffer)
X(PFNGLBUFFERDATAPROC, glBufferData)
X(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray)
X(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer)

X(PFNGLCREATESHADERPROC, glCreateShader)
X(PFNGLSHADERSOURCEPROC, glShaderSource)
X(PFNGLCOMPILESHADERPROC, glCompileShader)
X(PFNGLCREATEPROGRAMPROC, glCreateProgram)
X(PFNGLATTACHSHADERPROC, glAttachShader)
X(PFNGLLINKPROGRAMPROC, glLinkProgram)
X(PFNGLUSEPROGRAMPROC, glUseProgram)
X(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation)
X(PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv)

X(PFNGLGETSHADERIVPROC, glGetShaderiv)
X(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog)
X(PFNGLGETPROGRAMIVPROC, glGetProgramiv)
X(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog)
X(PFNGLDELETESHADERPROC, glDeleteShader)
X(PFNGLUNIFORM1IPROC, glUniform1i)
X(PFNGLUNIFORM1FPROC, glUniform1f)
X(PFNGLUNIFORMMATRIX3FVPROC, glUniformMatrix3fv)
X(PFNGLUNIFORM3FPROC, glUniform3f)
X(PFNGLDELETEPROGRAMPROC, glDeleteProgram)
X(PFNGLGENERATEMIPMAPPROC, glGenerateMipmap)
X(PFNGLACTIVETEXTUREPROC, glActiveTexture)
X(PFNGLDELETEBUFFERSPROC, glDeleteBuffers)
X(PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays)